# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Dynamically set MY_DATE environment variable
        run: echo "buildId=Parabank-$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Runs a set of commands using the runners shell
      - name: Deploy Environment
        # You may pin to the exact commit or the version.
        # uses: parasoft/deploy-environment-action@ea4c180723d6eb7858e41fa89c2af734ddd8c8b5
        uses: parasoft/deploy-environment-action@1.0.0
        with:
          # CTP URL
          ctpUrl: 'http://40.83.216.71/em'
          # CTP Username
          ctpUsername: 'admin'
          # CTP Password
          ctpPassword: 'admin'
          # Name of the system
          system: 'ParaBank'
          # Name of the environment
          environment: 'Golden'
          # Name of the environment instance to provision
          instance: 'Negative'
          # Fail action and abort on provisioning failure
          abortOnFailure: # 'false'
          
      - name: Execute Job
        # You may pin to the exact commit or the version.
        # uses: parasoft/execute-job-action@4ff52dfe0b1abb285d1e94418d9b6015bbb5f6bc
        uses: parasoft/execute-job-action@1.0.0
        with:
          # CTP URL
          ctpUrl: 'http://40.83.216.71/em'
          # CTP Username
          ctpUsername: 'admin'
          # CTP Password
          ctpPassword: 'admin'
          # CTP Test Execution Job Name
          ctpJob: 'StatusTest'
          # Publish test execution results to DTP
          publishReport: # 'true'
          # DTP URL
          dtpUrl: # 'http://34.219.97.185:8080/grs'
          # DTP Username
          dtpUsername: # 'demo'
          # DTP Password
          dtpPassword: # 'demo-user'
          # DTP Project Name
          dtpProject: # 'All Projects'
          # Build ID to send to DTP
          buildId: # '1'
          # Session Tag to send to DTP
          sessionTag: # 'GitHubTest'
          # Append the test variable set environment name to the session tag
          appendEnvironment: # optional
      - name: Disconnect Action
        # You may pin to the exact commit or the version.
        # uses: parasoft/disconnect-server-action@c07b9be852bd7309ab6b840d77e6bd4f079cb082
        uses: parasoft/disconnect-server-action@1.0.0
        with:
          # CTP URL
          ctpUrl: 'http://40.83.216.71/em'
          # CTP Username
          ctpUsername: 'admin'
          # CTP Password
          ctpPassword: 'admin'
          # Used to specify server by host or name
          serverMatch: 'host'
          # Host or name of the server
          server: 'ctpsprinttest2.internal.cloudapp.net'
